// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtnCCGW1scwq-P1aCita9GbgMZ3epdnM',
    appId: '1:277748821679:web:44b5f17a0070fdc0b7ee5a',
    messagingSenderId: '277748821679',
    projectId: 'excelerate-learninghub',
    authDomain: 'excelerate-learninghub.firebaseapp.com',
    storageBucket: 'excelerate-learninghub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOAqv6LepAXvBeJeez6uE95WXAGThNcw',
    appId: '1:277748821679:android:e5857b5cb5ab9f5cb7ee5a',
    messagingSenderId: '277748821679',
    projectId: 'excelerate-learninghub',
    storageBucket: 'excelerate-learninghub.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtnCCGW1scwq-P1aCita9GbgMZ3epdnM',
    appId: '1:277748821679:web:f730134050d296d1b7ee5a',
    messagingSenderId: '277748821679',
    projectId: 'excelerate-learninghub',
    authDomain: 'excelerate-learninghub.firebaseapp.com',
    storageBucket: 'excelerate-learninghub.firebasestorage.app',
  );
}
