import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

import 'screens/sign_in_screen.dart';
import 'screens/sign_up_screen.dart';
import 'screens/home_screen.dart';
import 'screens/program_listing_screen.dart';
import 'screens/program_details_screen.dart';
import 'services/program_service.dart';
import 'screens/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Handle Firebase initialization for both web and mobile
  if (kIsWeb) {
    await Firebase.initializeApp(
      options: const FirebaseOptions(
        apiKey: "AIzaSyDrtnCCGW1scwq-P1aCita9GbgMZ3epdnM",
        authDomain: "excelerate-learninghub.firebaseapp.com",
        projectId: "excelerate-learninghub",
        storageBucket: "excelerate-learninghub.firebasestorage.app",
        messagingSenderId: "277748821679",
        appId: "1:277748821679:web:44b5f17a0070fdc0b7ee5a",
      ),
    );
  } else {
    // ✅ Uses the default firebase_options.dart generated by FlutterFire CLI
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  // ✅ Preload mock program data
  final programs = await ProgramService().loadPrograms();
  debugPrint('Loaded ${programs.length} programs from JSON!');

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Excelerate Programs',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.grey,
        scaffoldBackgroundColor: Colors.white,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0,
          foregroundColor: Colors.black,
          titleTextStyle: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: Colors.black,
          ),
        ),
      ),

      // ✅ Start from the Splash Screen
      initialRoute: '/splash',

      routes: {
        '/splash': (context) => const SplashScreen(),
        '/signIn': (context) => const SignInScreen(),
        '/signUp': (context) =>
            const SignUpScreen(), // fixed: should point to SignUpScreen
        '/home': (context) => const HomeScreen(),
        '/programListing': (context) => const ProgramListingScreen(),
      },

      // ✅ Dynamic program details route
      onGenerateRoute: (settings) {
        if (settings.name == '/programDetails') {
          final dynamic program = settings.arguments;
          return MaterialPageRoute(
            builder: (context) => ProgramDetailsScreen(
              program: program,
              title: '',
              date: '',
              category: '',
              description: '',
            ),
          );
        }
        return null;
      },
    );
  }
}
